# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.5 on 2017-01-31 19:32
=======
# Generated by Django 1.10.5 on 2017-01-31 19:30
>>>>>>> 0a0bb9aaa28a15fa188543de4773db698c81080c
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='sub_population',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.SubPopulation'),
            preserve_default=False,
        ),
    ]
