# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_datapoint_sub_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethnicity',
            name='populations',
            field=models.ManyToManyField(to='display.SubPopulation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicities',
            field=models.ManyToManyField(through='display.UserEthnicity', to='display.Ethnicity'),
        ),
        migrations.AddField(
            model_name='subpopulation',
            name='code',
            field=models.CharField(default='nul', max_length=5),
            preserve_default=False,
        ),
    ]
